### ISSUE TITLE
Access elements

### ISSUE THREAD

**Issue by DJDDDM** [tensor-compiler/taco#181] opened 2019-01-08 12:57 UTC
How to access the elements of a tensor?
I want to write a testsuite so I can start working with taco using TDD.

**Comment by DJDDDM** [comment] 2019-01-10 10:21
In Case someone stumbles upon this:

for (int i = 0; i < Actual.getStorage().getValues().getSize(); i++){
		int actual = static_cast<const int*>(Actual.getStorage().getValues().getData())[i];
		int expected = static_cast<const int*>(Expected.getStorage().getValues().getData())[i];
		assert(actual == expected);
	}

**Comment by oicirtap** [comment] 2019-01-10 15:10
There are currently two approaches to accessing the elements in a tensor. The first one (as you noted in your example above) is to access the underlying `Storage` object in the tensor, and operate on the data stored in it. The second one is to use the `begin()` and `end()` methods in the Tensor class to obtain an iterator over the elements of the tensor.

We are currently working on a new interface for tensor objects which will extend the set of methods which can be used to access tensor values. It will allow to access specific elements or element ranges for example.

**Comment by DJDDDM** [comment] 2019-01-10 15:12
Can you show an example for the begin() end() method?

**Comment by oicirtap** [comment] 2019-01-10 15:23
The `writeTNS ` function in file_io_tns.cpp:104 implicitly uses `begin()` and `end()` by iterating over the elements of a tensor in the for loop of line 105.

https://github.com/tensor-compiler/taco/blob/6a75daccc1844db69d5f93f0bc4520c5f27b7b5a/src/storage/file_io_tns.cpp#L104

**Comment by fredrikbk** [comment] 2019-02-26 14:35
Duplicate of #168

**Closed by fredrikbk** 2019-02-26 14:35 UTC
