### ISSUE TITLE
Build error: cannot call member function ‘void taco::Iterators::createAccessIterators(taco::Access, taco::Format, taco::ir::Expr)’ without object

### ISSUE THREAD

**Issue by rjw245** [tensor-compiler/taco#274] opened 2019-11-04 16:15 UTC
I see the following error when building on Ubuntu 16.04

```
[  3%] Building CXX object src/CMakeFiles/taco.dir/lower/iterator.cpp.o
/home/riley/compilers/proj/rjw2624_hh26833_compilers_final_proj/taco/src/lower/iterator.cpp: In instantiation of ‘taco::Iterators::Iterators(taco::IndexStmt, const std::map<taco::TensorVar, taco::ir::Expr>&)::<lambda(auto:3)> [with auto:3 = const taco::AccessNode*]’:
/usr/include/c++/5/type_traits:2346:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__success_type<decltype (declval<_Fn>()((declval<_Args>)()...))> std::__result_of_other_impl::_S_test(int) [with _Fn = taco::Iterators::Iterators(taco::IndexStmt, const std::map<taco::TensorVar, taco::ir::Expr>&)::<lambda(auto:3)>&; _Args = {const taco::AccessNode*}]’
/usr/include/c++/5/type_traits:2357:55:   required from ‘struct std::__result_of_impl<false, false, taco::Iterators::Iterators(taco::IndexStmt, const std::map<taco::TensorVar, taco::ir::Expr>&)::<lambda(auto:3)>&, const taco::AccessNode*>’
/usr/include/c++/5/type_traits:2361:12:   required from ‘class std::result_of<taco::Iterators::Iterators(taco::IndexStmt, const std::map<taco::TensorVar, taco::ir::Expr>&)::<lambda(auto:3)>&(const taco::AccessNode*)>’
/usr/include/c++/5/functional:2053:9:   required by substitution of ‘template<class _Functor, class, class> std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = taco::Iterators::Iterators(taco::IndexStmt, const std::map<taco::TensorVar, taco::ir::Expr>&)::<lambda(auto:3)>; <template-parameter-1-2> = void; <template-parameter-1-3> = <missing>]’
/home/riley/compilers/proj/rjw2624_hh26833_compilers_final_proj/taco/src/lower/iterator.cpp:393:6:   required from here
/home/riley/compilers/proj/rjw2624_hh26833_compilers_final_proj/taco/src/lower/iterator.cpp:392:28: error: cannot call member function ‘void taco::Iterators::createAccessIterators(taco::Access, taco::Format, taco::ir::Expr)’ without object
       createAccessIterators(Access(n), format, tensorIR);
                            ^
src/CMakeFiles/taco.dir/build.make:638: recipe for target 'src/CMakeFiles/taco.dir/lower/iterator.cpp.o' failed
make[2]: *** [src/CMakeFiles/taco.dir/lower/iterator.cpp.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'src/CMakeFiles/taco.dir/all' failed
make[1]: *** [src/CMakeFiles/taco.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

I've got g++ 5.5.0 installed:
g++ (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010

I was able to successfully build on a different machine running Ubuntu 18.04. Does anyone know the cause of this error?

**Comment by rjw245** [comment] 2019-11-04 16:25
cmake version 3.5.1

**Comment by stephenchouca** [comment] 2019-11-06 01:34
Might be caused by [this GCC bug](https://stackoverflow.com/questions/32097759/calling-this-member-function-from-generic-lambda-clang-vs-gcc). Do you still get an error if you add `this->` in front of the call to `createAccessIterators`?

**Comment by dongxiao92** [comment] 2019-11-06 02:33
@stephenchouca Thanks for your reply. Add `this->` resolves the error but new errors occur.

```
/home/dongxiao/working/taco-new-scheling-lang/test/tests-scheduling.cpp: In member function ‘virtual void scheduling_lowerSparseCopy_Test::TestBody()’:
/home/dongxiao/working/taco-new-scheling-lang/test/tests-scheduling.cpp:116:38: error: call of overloaded ‘Tensor(const char [2], <brace-enclosed initializer list>, <brace-enclosed initializer list>)’ is ambiguous
   Tensor<double> A("A", {8}, {Sparse});
                                      ^
In file included from /home/dongxiao/working/taco-new-scheling-lang/test/test.h:11:0,
                 from /home/dongxiao/working/taco-new-scheling-lang/test/tests-scheduling.cpp:3:
/home/dongxiao/working/taco-new-scheling-lang/include/taco/tensor.h:513:3: note: candidate: taco::Tensor<CType>::Tensor(std::__cxx11::string, std::vector<int>, taco::Format) [with CType = double; std::__cxx11::string = std::__cxx11::basic_string<char>]
   Tensor(std::string name, std::vector<int> dimensions, Format format)
   ^
/home/dongxiao/working/taco-new-scheling-lang/include/taco/tensor.h:508:3: note: candidate: taco::Tensor<CType>::Tensor(std::__cxx11::string, std::vector<int>, taco::ModeFormat) [with CType = double; std::__cxx11::string = std::__cxx11::basic_string<char>]
   Tensor(std::string name, std::vector<int> dimensions, 

```

**Comment by Infinoid** [comment] 2020-10-21 18:02
Hi @rjw245, @dongxiao92,

Is this still an issue with the current version (master branch) of Taco?

**Comment by ByzanTine** [comment] 2020-12-07 06:13
Hi, I am still having the issue above, I am building with gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12).

**Comment by Infinoid** [comment] 2020-12-07 14:42
@ByzanTine Thanks, you are right.

I made an ubuntu:16.04 docker container and tried to build, and got the same issue.  Adding `this->` fixes it.  I see the failures in the scheduling tests that @dongxiao92 mentioned, too.  Those can be fixed by changing `{Dense}` to `Format({Dense})`.

I will post a patch to fix it.

**Closed** 2020-12-07 15:36 UTC
