### ISSUE TITLE
evaluation hangs

### ISSUE THREAD

**Issue by jcrbloch** [tensor-compiler/taco#195] opened 2019-02-07 09:29 UTC
I have a very simple example of a contraction which hangs when evaluating the expression. I reduced the problem to a minimal example. In the code below there is one contraction that works and the second that hangs. The only difference between both expressions is the **order of the indices yb and zf** in the output tensor, everything else is identical. I add the stored input tensor T as zip file, so that you can check the issue more easily.

[T.tns.zip](https://github.com/tensor-compiler/taco/files/2840113/T.tns.zip)

```
#include <iostream>
#include "taco.h"
using namespace std;
using namespace taco;

int main()
{
	Tensor<double> T({2,2,2,2,2,2},Format({Dense,Dense,Dense,Dense,Dense,Dense}));
	T = read("T.tns",Format({Dense,Dense,Dense,Dense,Dense,Dense}));
	cout << T << endl;

	Tensor<int> reductor("reductor",{2},Format({Sparse}));
	reductor.insert({0},1);
	reductor.pack();

	IndexVar i,yf,zf,yb,zb,x;

	Tensor<double> Tred1("Tred1",{2,2,2,2,2},Format({Dense,Dense,Dense,Dense,Dense}));
	Tred1(i,yf,yb,zf,zb) = reductor(x) * T(x,i,yf,yb,zf,zb);
	Tred1.evaluate(); 
	cout << Tred1 << endl;

	Tensor<double> Tred2("Tred2",{2,2,2,2,2},Format({Dense,Dense,Dense,Dense,Dense}));
	Tred2(i,yf,zf,yb,zb) = reductor(x) * T(x,i,yf,yb,zf,zb);
	Tred2.evaluate(); 
	cout << Tred2 << endl;
}
```

**Comment by jcrbloch** [comment] 2019-02-07 13:56
Now I just had a thought that scared me. Is taco written such that one can/should only make a reduction of a single index? Right now I am using taco to reduce multiple modes at once. It would be nice to get a feedback about this too.

**Comment by DJDDDM** [comment] 2019-02-14 14:15
Check the online tool in such cases it has better error messages currently.

The problem is, that taco currently can't deal with swapping indices if you have i,j writing j,i somewhere in the same equation is an error but can be fixed by using the transpose functionality. Early Summer the new version is expected.

**Comment by Infinoid** [comment] 2020-09-28 19:13
This program runs successfully on the current version of taco (master branch).  I get the following output:

```
Tred1 (2x2x2x2x2) ({dense},{dense},{dense},{dense},{dense}; 0,1,2,3,4):
dense (0): 
  [2]
dense (1): 
  [2]
dense (2): 
  [2]
dense (3): 
  [2]
dense (4): 
  [2]
[1, 0, 0, 0.218635, 0, 0.218635, 0.218635, 0, 0, 0.218635, 0.218635, 0, 0.218635, 0, 0, 0.0478013, 0, 0.218635, 0.218635, 0, 0.218635, 0, 0, 0.0478013, 0.218635, 0, 0, 0.0478013, 0, 0.0478013, 0.0478013, 0]
Tred2 (2x2x2x2x2) ({dense},{dense},{dense},{dense},{dense}; 0,1,2,3,4):
dense (0): 
  [2]
dense (1): 
  [2]
dense (2): 
  [2]
dense (3): 
  [2]
dense (4): 
  [2]
[1, 0, 0, 0.218635, 0, 0.218635, 0.218635, 0, 0, 0.218635, 0.218635, 0, 0.218635, 0, 0, 0.0478013, 0, 0.218635, 0.218635, 0, 0.218635, 0, 0, 0.0478013, 0.218635, 0, 0, 0.0478013, 0, 0.0478013, 0.0478013, 0]
```

**Closed** 2020-09-29 03:29 UTC
